export let GROUPS: ({[key: number]: string}) = {
  0: 'Pre-Q round',
  1: 'Q-First round',
  2: 'Q-Second round',
  3: 'Qualifying',
  4: 'First',
  5: 'Second',
  6: 'Third',
  7: 'Fourth',
  8: 'Robin',
  9: 'Quarterfinals',
  10: 'Semifinals',
  11: 'Olympics',
  12: 'Final',
  13: 'Rubber 1',
  14: 'Rubber 2',
  15: 'Rubber 3',
  16: 'Rubber 4',
  17: 'Rubber 5',
  20: 'N/A',
}

export let SHORT_GROUPS: ({[key: number]: string}) = {
  0: 'Pre-Q',
  1: 'Q-First',
  2: 'Q-Second',
  3: 'Qualifying',
  4: 'R1',
  5: 'R2',
  6: 'R3',
  7: 'R4',
  8: 'Robin',
  9: 'QF',
  10: 'SF',
  11: 'Olympics',
  12: 'F',
  13: 'Rubber 1',
  14: 'Rubber 2',
  15: 'Rubber 3',
  16: 'Rubber 4',
  17: 'Rubber 5',
  20: 'N/A',
}
